name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install backend deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint

      - name: Test (Jest)
        env:
          MONGO_URI: mongodb://localhost:27017/test
          JWT_SECRET: test-secret-should-be-long-enough_12345678901234567890
          ACCESS_TOKEN_SECRET: test-access-token-secret-should-be-long-enough_12345678901234567890
          CORS_ORIGIN: http://localhost:5173
        run: npm test

  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @redocly/cli
      - name: Lint OpenAPI
        run: redocly lint docs/openapi.yml
